spring:
  application:
    name: Testagram
  config:
    import: "classpath:security.yaml"

  datasource:
    url: jdbc:mysql://localhost:3306/testagram
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  error:
    include-message: always

jwt:
  secret:
    key: Thecurrenttimeis922AMonMay30th2025mynameisGunhoJangToissueatokenusingJWTAsecretkeyisrequired

##